# Generated by Django 5.2.4 on 2026-06-29 14:23

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(max_length=124)),
                ('surname', models.CharField(max_length=124)),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^(\\+7|8)\\d{10}$', 'Формат: 8XXXXXXXXXX или +7XXXXXXXXXX')])),
                ('github_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(), django.core.validators.RegexValidator('^https?://(www\\.)?github\\.com/.*$')])),
                ('about', models.TextField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorites', models.ManyToManyField(blank=True, related_name='interested_users', to='projects.project')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
